# Classes for parsing requirements.txt files as produced by the
# pip-compile program.  Can be used for dependency graph analysis.
# Chris Joakim, 2025

import traceback

from src.io.fs import FS


class Libraries:

    def __init__(self):
        self.libs = dict()

    def add_library(self, lib: dict):
        if lib is not None:
            self.libs[lib.name] = lib

    def traverse_graph(self):
        pass  # TODO


class RequirementsTxtParser:

    def __init__(self):
        self.data = None

    def parse(self, filename: str) -> list:
        self.data = dict()
        self.data["libname"] = None
        self.data["libvers"] = None
        self.data["infile"] = None
        self.data["dependencies"] = dict()
        try:
            infile = "data/pip/{}".format(filename.strip())
            libname = filename.split(".")[0]
            print("infile: {} -> libname: {}".format(infile, libname))
            lines = FS.read_lines(infile)
            #print("{} lines in {}".format(len(lines), infile))
            self.data["infile"] = infile
            self.data["libname"] = libname
            curr_lib = None

            for line in lines:
                if "==" in line:  # boto3==1.38.9
                    curr_lib = line.split("==")[0]
                    lib_vers = line.split("==")[1].rstrip()
                    if curr_lib == libname:
                        self.data["libvers"] = lib_vers
                    else:
                        self.data["dependencies"][curr_lib] = lib_vers
        except Exception as e:
            self.data["exception"] = str(e)
            print(str(e))
            print(traceback.format_exc())

        return self.data

class SampleRequirements:

    @classmethod
    def project_sample(cls):
        return """
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile boto3.in
#
boto3==1.38.9
    # via -r boto3.in
botocore==1.38.9
    # via
    #   boto3
    #   s3transfer
jmespath==1.0.1
    # via
    #   boto3
    #   botocore
python-dateutil==2.9.0.post0
    # via botocore
s3transfer==0.12.0
    # via boto3
six==1.17.0
    # via python-dateutil
urllib3==2.4.0
    # via botocore
""".strip()
    